### ISSUE TITLE
Last 7 days or custom length?

### ISSUE THREAD

**Issue by OmgImAlexis** [shroudedcode/devstats#4]
I'd love to see a weekly or x days option as opposed to a single day.

**Comment by niklashigi** [comment]
This would be really useful. What do you think about this?

- a `--week` (`-w`) option that
  - shows the stats since the first day of the current week (inferred from timezone)
  - allows switching between weeks using the keyboard (jumps 7 days per press)
- a `--days <days>` (`-d`) option that
  - shows the stats for the last `<days>` days
  - allows moving the timeframe using the keyboard (only jumps 1 day per press)

**Comment by OmgImAlexis** [comment]
That sounds perfect.

**Comment by niklashigi** [comment]
@OmgImAlexis Could you give #5 a try? The implementation ended up being fairly complex and I want to make sure that everything works as expected.
